ideahubio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('create_idea', views.IdeaCreate.as_view(), name='create_idea'),
    path('accounts/signup/', views.signup, name='signup'),
    path('ideas/', views.IdeaList.as_view(), name='list_ideas'),
    path('ideas/<int:idea_id>', views.ideas_detail, name='detail'),
    path('ideas/delete/<int:pk>', views.IdeaDelete.as_view(), name='idea_delete'),
    path('ideas/update/<int:pk>', views.IdeaUpdate.as_view(), name='idea_update'),
    path('public/', views.public_list, name='list_public'),
    path('ideas/makepublic/<int:idea_id>', views.make_public, name='make_public'),
    path('ideas/makeprivate/<int:idea_id>', views.make_private, name='make_private'),
    path('ideas/<int:idea_id>/add_photo/', views.add_photo, name='add_photo'),
    path('ideas/<int:idea_id>/add_logo', views.add_logo, name='add_logo'),
    path('ideas/<int:idea_id>/remove_logo/', views.delete_logo, name='remove_logo'),
    path('ideas/<int:photo_id>/<int:idea_id>/delete_photo/', views.delete_photo, name='delete_photo'),
    path('ideas/<int:idea_id>/add_employee/', views.add_employee, name='add_employee'),
    path('ideas/<int:idea_id>/<int:employee_id>/delete_employee/', views.delete_employee, name='delete_employee'),
    path('ideas/<int:pk>/update_employee/', views.UpdateEmployee.as_view(), name='update_employee'),
    path('ideas/<int:employee_id>/update_employee_done/', views.update_employee_done, name='update_employee_done'),
    path('ideas/<int:idea_id>/like_idea', views.like_idea, name='like_idea'),
    path('ideas/<int:idea_id>/unlike_idea', views.unlike_idea, name='unlike_idea'),
    #PASSWORD RESET URLS
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    #Chatroom URLS
    path('chat/', views.chatindex, name='chatindex'),
    path('chat/<int:room_name>/', views.room, name='room'),
    path('chat/storemessage/<int:room_id>/', views.store_message, name='store_message')
]

main_app/models.py
from django.db import models
from django.shortcuts import reverse
from datetime import date, datetime
from django.contrib.auth.models import User
# Create your models here.



INDUSTRIES = (
    ('Advertising','Advertising'),
    ('Aerospace','Aerospace'),
    ('Agriculture','Agriculture'),
    ('Air Transport','Air Transport'),
    ('Alcoholic Beverages','Alcoholic Beverages'),
    ('Alternative Energy','Alternative Energy'),
    ('Architectural Services','Architectural Services'),
    ('Automotive','Automotive'),
    ('Banking','Banking'),
    ('Business Services','Business Services'),
    ('Chemical Manufacturing','Chemical Manufacturing'),
    ('Construction','Construction'),
    ('Credit Unions','Credit Unions'),
    ('Cruise Ships','Cruise Ships'),
    ('Defense','Defense'),
    ('Dentists','Dentists'),
    ('Drug Manufacturers','Drug Manufacturers'),
    ('Education','Education'),
    ('Electric Utilities','Electric Utilities'),
    ('Eletronics Manufacturing','Eletronics Manufacturing'),
    ('Energy & Natural Resources','Energy & Natural Resources'),
    ('Farming','Farming'),
    ('Finance','Finance'),
    ('Food & Beverages','Food & Beverages'),
    ('For-profit Education','For-profit Education'),
    ('Funeral Services','Funeral Services'),
    ('Gambling & Casinos','Gambling & Casinos'),
    ('Gas & Oil','Gas & Oil'),
    ('General Contractors','General Contractors'),
    ('Health Services','Health Services'),
    ('Home Builders','Home Builders'),
    ('Hotels, Motels & Tourism','Hotels, Motels & Tourism'),
    ('Insurance','Insurance'),
    ('Internet','Internet'),
    ('Liquor, Wine & Beer','Liquor, Wine & Beer'),
    ('Logging','Logging'),
    ('Marine Transport','Marine Transport'),
    ('Meat processing & products','Meat processing & products'),
    ('Medical Supplies','Medical Supplies'),
    ('Music Production','Music Production'),
    ('Non-profit Organization','Non-profit Organization'),
    ('Nutritional Supplements','Nutritional Supplements'),
    ('Oil & Gas','Oil & Gas'),
    ('Payday Lenders','Payday Lenders'),
    ('Pharmaceutical Manufacturing','Pharmaceutical Manufacturing'),
    ('Power Utilities','Power Utilities'),
    ('Printing & Publishing','Printing & Publishing'),
    ('Radio/TV Stations','Radio/TV Stations'),
    ('Real Estate','Real Estate'),
    ('Record Label','Record Label'),
    ('Recreation','Recreation'),
    ('Restuarants','Restuarants'),
    ('Retail Sales','Retail Sales'),
    ('Savings & Loans','Savings & Loans'),
    ('Schools/Education','Schools/Education'),
    ('Securities & Investments','Securities & Investments'),
    ('Teachers Unions','Teachers Unions'),
    ('Telecom Services','Telecom Services'),
    ('Tobacco','Tobacco'),
    ('Transportation','Transportation'),
    ('Trucking','Trucking'),
    ('TV Production','TV Production'),
    ('Venture Capital','Venture Capital'),
    ('Other','Other'),
)



class Idea(models.Model):
  name = models.CharField(max_length=70)
  logo_url = models.CharField(default="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/ProhibitionSign2.svg/1200px-ProhibitionSign2.svg.png", max_length=300)
  description = models.TextField(max_length=10000)
  is_public = models.BooleanField(default=False)
  people_interested = models.CharField(max_length=100)
  date = models.DateTimeField(default=datetime.now, blank=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  industry = models.CharField(
    max_length = 70,
    choices=INDUSTRIES,
    default=INDUSTRIES[0]
  )

  def __str__(self):
    return f"{self.name}"
  
  def get_absolute_url(self):
      return reverse("detail", kwargs={"idea_id": self.id})

class Liked(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
# TEST
  def __str__(self):
    return f"{self.user.username}"

class Employee(models.Model):
  role = models.CharField(max_length=80)
  auth_level = models.IntegerField()
  function = models.CharField(max_length=250)
  idea = models.ForeignKey(Idea, on_delete=models.CASCADE)

  def __str__(self):
    return f"Employee for idea_id {self.idea_id}"
  

# class Industry(models.Model):
#   industry = models.CharField(
#     max_length = 70,
#     choices=INDUSTRIES,
#     default=INDUSTRIES[len(INDUSTRIES) - 1]
#   )
#   idea = models.ForeignKey(Idea, on_delete=models.CASCADE)

  # def __str__(self):
  #   return f"The industry is {self.get_industry_display()} for idea_id: {self.idea_id}"
# add this message
class Photo(models.Model):
  url = models.CharField(max_length=200)
  idea = models.ForeignKey(Idea, on_delete=models.CASCADE)

  def __str__(self):
      return f"Photo for idea_id {self.idea_id} @ {self.url}"
  
class Message(models.Model):
  text = models.CharField(max_length=1000)
  user = models.CharField(max_length=500)

  def __str__(self):
    return self.text

main_app/forms.py
from django.forms import ModelForm
# Stuff to make email work
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserCreationForm
from .models import Idea, Photo, Employee, Liked, Message

from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView

import uuid
import boto3

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'idea-hub-bucket'

# Create your views here.
def home(request):
  return render(request, 'home.html')

@login_required
def ideas_detail(request, idea_id):
  idea = Idea.objects.get(id=idea_id)
  users_liked = len(idea.liked_set.all())
  user_liked = idea.liked_set.filter(user=request.user).exists()
  return render(request, 'ideas/detail.html', {'idea': idea, 'user_liked': user_liked, 'users_liked': users_liked})

@login_required
def public_list(request):
  idea = Idea.objects.filter(is_public=True)
  idea = idea.exclude(user=request.user)
  return render(request, 'main_app/public_list.html', {'idea': idea})

@login_required
def make_public(request, idea_id):
  idea = Idea.objects.get(id=idea_id)
  idea.is_public = True
  idea.save()
  return redirect('detail', idea_id=idea_id)

@login_required
def make_private(request, idea_id):
  idea = Idea.objects.get(id=idea_id)
  idea.is_public = False
  idea.save()
  return redirect('detail', idea_id=idea_id)

@login_required
def store_message(request, room_id):
  message = Message.objects.create(
    user = request.POST.get('username'),
    text = request.POST.get('message'),
    room = room_id
  )
  message.save()
  return redirect('room', room_name=room_id)

# def update_employee(request, idea_id, employee_id):
#   idea = Idea.objects.get(id=idea_id)
#   employee = Employee.objects.get(id=employee_id)
#   return render(request, 'main_app/employee_form.html', {
#     'idea': idea,
#     'employee': employee
#   })



class UpdateEmployee(LoginRequiredMixin, UpdateView):
  model = Employee
  fields = ['role', 'function', 'auth_level']

@login_required
def update_employee_done(request, employee_id):
  employee = Employee.objects.get(id=employee_id)
  employee.auth_level = request.POST.get('authlevel')
  employee.role = request.POST.get('role')
  employee.function = request.POST.get('function')
  employee.save()
  return redirect('detail', idea_id=employee.idea_id)

@login_required
def like_idea(request, idea_id):
  idea = Idea.objects.get(id=idea_id)
  liked = Liked.objects.create(user=request.user, idea=idea)
  liked.save()
  return redirect('detail', idea_id=idea_id)
  
@login_required
def unlike_idea(request, idea_id):
  idea = Idea.objects.get(id=idea_id)
  Liked.objects.get(idea=idea, user=request.user).delete()
  return redirect('detail', idea_id=idea_id)

@login_required
def delete_photo(request, photo_id, idea_id):
  Photo.objects.get(id=photo_id).delete()
  return redirect('detail', idea_id=idea_id)

@login_required
def delete_logo(request, idea_id):
  idea = Idea.objects.get(id=idea_id)
  idea.logo_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/ProhibitionSign2.svg/1200px-ProhibitionSign2.svg.png"
  idea.save()
  return redirect('detail', idea_id=idea_id)

@login_required
def add_photo(request, idea_id):
  # photo-file will be the "name" attribute on the <input type="file">
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # need a unique "key" for S3 / needs image file extension too
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    # just in case something goes wrong
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      # build the full url string
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      # we can assign to cat_id or cat (if you have a cat object)
      photo = Photo(url=url, idea_id=idea_id)
      photo.save()
    except Exception as err:
      print('An error occurred uploading file to S3: %s' % err)
  return redirect('detail', idea_id=idea_id)

@login_required
def delete_employee(request, employee_id, idea_id):
  employee = Employee.objects.get(id=employee_id)
  print('hit this')
  employee.delete()
  return redirect('detail', idea_id=idea_id)

@login_required
def add_employee(request, idea_id):
  employee = Employee.objects.create(
    role=request.POST['role'], 
    auth_level=request.POST['authlevel'], 
    function=request.POST['function'],
    idea_id = idea_id
  )
  employee.save()
  return redirect('detail', idea_id=idea_id)

@login_required
def add_logo(request, idea_id):
  # get the idea, remove the old URL, replace it.
  idea = Idea.objects.get(id=idea_id)
  # photo-file will be the "name" attribute on the <input type="file">
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # need a unique "key" for S3 / needs image file extension too
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    # just in case something goes wrong
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      # build the full url string
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      # we can assign to cat_id or cat (if you have a cat object)
      idea.logo_url = url
      idea.save()
    except Exception as err:
      print('An error occurred uploading file to S3: %s' % err)
  return redirect('detail', idea_id=idea_id)  


def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

# Create your CBV's here.
class IdeaCreate(LoginRequiredMixin, CreateView):
  model = Idea
  fields = ['name', 'description', 'industry', 'is_public']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class IdeaList(LoginRequiredMixin, ListView):
  model = Idea

class IdeaDelete(LoginRequiredMixin, DeleteView):
  model = Idea
  success_url = '/ideas/'

class IdeaUpdate(LoginRequiredMixin, UpdateView):
  model = Idea
  fields = ['name', 'description', 'industry', 'is_public']

#CHAT ROOM CODE
@login_required
def chatindex(request):
  return render(request, 'chat/index.html')

@login_required
def room(request, room_name):
    idea = Idea.objects.get(id=room_name)
    return render(request, 'chat/room.html', {
        'room_name': room_name,
        'idea': idea
    })

main_app/templates/ideas/detail.html
{% extends 'base.html' %}

{% block content %}
{% if idea.user != user and idea.is_public == False %}
<h1 style='color: white; margin-top: 2.5em;'>This idea is private</h1>
{% else %}

<div id='logo_card h-100' class="card text-center" style="width: 40%; margin: 1rem; min-width: 285px;">
  <div class="img-wrap">
    <img id='detail_logo' src="{{ idea.logo_url }}" style="width: 18rem; justify-self: center;" >
    {% if idea.logo_url != 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/ProhibitionSign2.svg/1200px-ProhibitionSign2.svg.png' and idea.user == user%}
    <a href="{% url 'remove_logo' idea.id %}"><i class="fas fa-times"></i></a>
    {% endif %}
  </div>
  {% if idea.user == user %}
  <div class="card-body" style='text-align: left;'>
    <form action="{% url 'add_logo' idea.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
        <input type="file" name="photo-file">
        <input type="submit" class="btn btn-primary" value="Upload Photo" style='margin-top: 0.4rem;'>
    </form>
  </div>
  {% else %}
  <div class='card-footer'>
    {% if idea.liked_set.all|length > 1 %}
    {{ idea.liked_set.all|length }} people liked this idea
    {% elif idea.liked_set.all|length == 1%}
    1 person liked this idea
    {% endif %}
  </div>
  {% endif %}
</div>



<div class="card text-center" style="width: 40%; margin: 1rem; min-width: 285px;">
  <div class="card-body" style='text-align: left;'>
    <h2 class="card-title">{{ idea.name }}</h2>
    <h4 class='card-subtitle'>{{ idea.industry }}</h4>
    {% if idea.user != user%}
    <p class="card-subtitle">Created by {{ idea.user }}</p>
    {% endif %}
    <br>
    <h5>Description: </h5>
    <p class="card-text">{{ idea.description }}</p>
    {% if idea.user == user %}
        {% if idea.is_public == False %}
          <a href="{%  url 'make_public' idea.id%}"><button class='btn btn-primary'>Make Public</button></a>
    {% else %}
      <a href="{%  url 'make_private' idea.id%}"><button class='btn btn-primary'>Make Private</button></a>
    {% endif %}
    <a href="{% url 'idea_update' idea.id %}"><button class='btn btn-secondary'>Edit Idea</button></a>
    <a href="{% url 'idea_delete' idea.id %}"><button class='btn btn-danger'>Delete Idea</button></a>
  {% endif %}

  {% if idea.user != user and not user_liked %}
      <a href="{% url 'like_idea' idea.id %}"><i class="far fa-thumbs-up fa-3x"></i></a>
  {% elif idea.user != user %}
      <a href="{% url 'unlike_idea' idea.id %}"><i class="fas fa-thumbs-up fa-3x"></i></a>
  {% endif %}
  {% if idea.is_public != False %}
      <a href="{% url 'room' idea.id %}"><i class="fas fa-comments fa-3x"></i></a>
  {% endif %}
  {% if idea.user == user and idea.is_public == True%}
  <div class='liked'>
    <br>
    {% if users_liked == 0 %}
    No one has liked your idea yet
    {% else %}
    {{ users_liked }} people like your idea
    {% endif %}
  </div>
  {% endif %}
  </div>
</div>

<div class="card text-center" style="width: 82.5%; margin: 1rem; min-width: 285px;">
  <div class="card-body" style='text-align: left;'>
    <h4 style='text-align: left;'>Organizational Structure</h4>
    {% if idea.user == user %}
    <div clas='employee-form'>
      <h6 style='display: inline-flex'>Add a employee</h6>
      <form action="{% url 'add_employee' idea.id %}" method="POST">
        {% csrf_token %}
        <input type="text" name='role' placeholder="Job Title">
        <input type="text" name='function' placeholder="Job Function">
        <input type="number" name="authlevel" placeholder="Authorization Level">
        <input type='submit' value='Add Employee'>
      </form>
    </div>
    {% endif %}
    <br>
    <div class='employee-list' style='display: flex; justify-content: center;'>
      <table style='text-align: center'>
        <thead>
          <tr>
            {% if idea.user == user %}
            <th>Controls</th>
            {% endif %}
            <th>Role</th>
            <th>Function</th>
            <th>Authorization</th>
          </tr>
        </thead>
        <tbody>
        {% for employee in idea.employee_set.all %}
          <tr>
            {% if idea.user == user %}
            <td>
              <a href="{% url 'update_employee' employee.id%}"><i class="fas fa-user-edit"></i></a>
              <a href="{% url 'delete_employee' idea.id employee.id%}"><i class="fas fa-trash-alt"></i></a>
            </td>
            {% endif %}
            <td>{{ employee.role }}</td>
            <td>{{ employee.function}}</td>
            <td>{{ employee.auth_level }}</td>
          <tr>
        {% empty %}
          <h4 style='display: block'> No employees listed yet </h4>
        {% endfor %}
        </tbody>
      </table>
    </div>

  </div>
</div>

<div class="card text-center" style="width: 82.5%; margin: 1rem; min-width: 285px;">
  <div class="card-body" style='text-align: left;'>
    <h4>Additional Photos</h4>
    {% if idea.user == user %}
    <form action="{% url 'add_photo' idea.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Upload Photo">
      <input type="file" name="photo-file">
    </form>
    {% endif %}
    {% for photo in idea.photo_set.all %}
    <div class="img-wrap">
      <img id='detail_logo' src="{{ photo.url }}" style="width: 18rem; justify-self: center;" >
      <a href="{% url 'delete_photo' photo.id idea.id%}"><i class="fas fa-times" style='color: black'></i></a>
    </div>
  {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
  {% endfor %}

  </div>
</div>

{% endif %}

{% endblock %}